/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : ClientId,
  'name' : string,
  'createdAt' : Timestamp,
  'businessName' : string,
  'email' : string,
  'phone' : string,
}
export type ClientId = bigint;
export interface CreateClientArgs {
  'name' : string,
  'businessName' : string,
  'email' : string,
  'phone' : string,
}
export interface CreateLinkArgs {
  'url' : string,
  'title' : string,
  'parentId' : bigint,
  'parentType' : ParentType,
}
export interface CreateNoteArgs {
  'content' : string,
  'parentId' : bigint,
  'parentType' : ParentType,
}
export interface CreateProjectArgs {
  'status' : ProjectStatus,
  'clientId' : ClientId,
  'name' : string,
  'description' : string,
  'deadline' : string,
  'paidAmount' : bigint,
  'budget' : bigint,
}
export interface CreateTaskArgs { 'name' : string, 'projectId' : ProjectId }
export interface DashboardStats {
  'activeProjects' : bigint,
  'totalClients' : bigint,
  'completedProjects' : bigint,
  'totalEarnings' : bigint,
}
export interface Link {
  'id' : LinkId,
  'url' : string,
  'title' : string,
  'createdAt' : Timestamp,
  'parentId' : bigint,
  'parentType' : ParentType,
}
export type LinkId = bigint;
export interface Note {
  'id' : NoteId,
  'content' : string,
  'createdAt' : Timestamp,
  'parentId' : bigint,
  'parentType' : ParentType,
}
export type NoteId = bigint;
export type ParentType = { 'Client' : null } |
  { 'Project' : null };
export interface Project {
  'id' : ProjectId,
  'status' : ProjectStatus,
  'clientId' : ClientId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'deadline' : string,
  'paidAmount' : bigint,
  'budget' : bigint,
}
export type ProjectId = bigint;
export type ProjectStatus = { 'InProgress' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface Task {
  'id' : TaskId,
  'name' : string,
  'createdAt' : Timestamp,
  'isDone' : boolean,
  'projectId' : ProjectId,
}
export type TaskId = bigint;
export type Timestamp = bigint;
export interface UpdateClientArgs {
  'id' : ClientId,
  'name' : string,
  'businessName' : string,
  'email' : string,
  'phone' : string,
}
export interface UpdateLinkArgs {
  'id' : LinkId,
  'url' : string,
  'title' : string,
}
export interface UpdateNoteArgs { 'id' : NoteId, 'content' : string }
export interface UpdateProjectArgs {
  'id' : ProjectId,
  'status' : ProjectStatus,
  'clientId' : ClientId,
  'name' : string,
  'description' : string,
  'deadline' : string,
  'paidAmount' : bigint,
  'budget' : bigint,
}
export interface UpdateTaskArgs {
  'id' : TaskId,
  'name' : string,
  'isDone' : boolean,
}
export interface _SERVICE {
  'createClient' : ActorMethod<[CreateClientArgs], Client>,
  'createLink' : ActorMethod<[CreateLinkArgs], Link>,
  'createNote' : ActorMethod<[CreateNoteArgs], Note>,
  'createProject' : ActorMethod<[CreateProjectArgs], Project>,
  'createTask' : ActorMethod<[CreateTaskArgs], Task>,
  'deleteClient' : ActorMethod<[ClientId], boolean>,
  'deleteLink' : ActorMethod<[LinkId], boolean>,
  'deleteNote' : ActorMethod<[NoteId], boolean>,
  'deleteProject' : ActorMethod<[ProjectId], boolean>,
  'deleteTask' : ActorMethod<[TaskId], boolean>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getClient' : ActorMethod<[ClientId], [] | [Client]>,
  'getClients' : ActorMethod<[], Array<Client>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getLinksByParent' : ActorMethod<[bigint, ParentType], Array<Link>>,
  'getNotesByParent' : ActorMethod<[bigint, ParentType], Array<Note>>,
  'getProject' : ActorMethod<[ProjectId], [] | [Project]>,
  'getProjectsByClient' : ActorMethod<[ClientId], Array<Project>>,
  'getTasksByProject' : ActorMethod<[ProjectId], Array<Task>>,
  'updateClient' : ActorMethod<[UpdateClientArgs], [] | [Client]>,
  'updateLink' : ActorMethod<[UpdateLinkArgs], [] | [Link]>,
  'updateNote' : ActorMethod<[UpdateNoteArgs], [] | [Note]>,
  'updateProject' : ActorMethod<[UpdateProjectArgs], [] | [Project]>,
  'updateTask' : ActorMethod<[UpdateTaskArgs], [] | [Task]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];