/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreateClientArgs = IDL.Record({
  'name' : IDL.Text,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ClientId = IDL.Nat;
export const Timestamp = IDL.Nat;
export const Client = IDL.Record({
  'id' : ClientId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ParentType = IDL.Variant({
  'Client' : IDL.Null,
  'Project' : IDL.Null,
});
export const CreateLinkArgs = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'parentId' : IDL.Nat,
  'parentType' : ParentType,
});
export const LinkId = IDL.Nat;
export const Link = IDL.Record({
  'id' : LinkId,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'parentId' : IDL.Nat,
  'parentType' : ParentType,
});
export const CreateNoteArgs = IDL.Record({
  'content' : IDL.Text,
  'parentId' : IDL.Nat,
  'parentType' : ParentType,
});
export const NoteId = IDL.Nat;
export const Note = IDL.Record({
  'id' : NoteId,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'parentId' : IDL.Nat,
  'parentType' : ParentType,
});
export const ProjectStatus = IDL.Variant({
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const CreateProjectArgs = IDL.Record({
  'status' : ProjectStatus,
  'clientId' : ClientId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'paidAmount' : IDL.Nat,
  'budget' : IDL.Nat,
});
export const ProjectId = IDL.Nat;
export const Project = IDL.Record({
  'id' : ProjectId,
  'status' : ProjectStatus,
  'clientId' : ClientId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'paidAmount' : IDL.Nat,
  'budget' : IDL.Nat,
});
export const CreateTaskArgs = IDL.Record({
  'name' : IDL.Text,
  'projectId' : ProjectId,
});
export const TaskId = IDL.Nat;
export const Task = IDL.Record({
  'id' : TaskId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isDone' : IDL.Bool,
  'projectId' : ProjectId,
});
export const DashboardStats = IDL.Record({
  'activeProjects' : IDL.Nat,
  'totalClients' : IDL.Nat,
  'completedProjects' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
});
export const UpdateClientArgs = IDL.Record({
  'id' : ClientId,
  'name' : IDL.Text,
  'businessName' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const UpdateLinkArgs = IDL.Record({
  'id' : LinkId,
  'url' : IDL.Text,
  'title' : IDL.Text,
});
export const UpdateNoteArgs = IDL.Record({
  'id' : NoteId,
  'content' : IDL.Text,
});
export const UpdateProjectArgs = IDL.Record({
  'id' : ProjectId,
  'status' : ProjectStatus,
  'clientId' : ClientId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'paidAmount' : IDL.Nat,
  'budget' : IDL.Nat,
});
export const UpdateTaskArgs = IDL.Record({
  'id' : TaskId,
  'name' : IDL.Text,
  'isDone' : IDL.Bool,
});

export const idlService = IDL.Service({
  'createClient' : IDL.Func([CreateClientArgs], [Client], []),
  'createLink' : IDL.Func([CreateLinkArgs], [Link], []),
  'createNote' : IDL.Func([CreateNoteArgs], [Note], []),
  'createProject' : IDL.Func([CreateProjectArgs], [Project], []),
  'createTask' : IDL.Func([CreateTaskArgs], [Task], []),
  'deleteClient' : IDL.Func([ClientId], [IDL.Bool], []),
  'deleteLink' : IDL.Func([LinkId], [IDL.Bool], []),
  'deleteNote' : IDL.Func([NoteId], [IDL.Bool], []),
  'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
  'deleteTask' : IDL.Func([TaskId], [IDL.Bool], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getClient' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
  'getClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getLinksByParent' : IDL.Func(
      [IDL.Nat, ParentType],
      [IDL.Vec(Link)],
      ['query'],
    ),
  'getNotesByParent' : IDL.Func(
      [IDL.Nat, ParentType],
      [IDL.Vec(Note)],
      ['query'],
    ),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
  'getProjectsByClient' : IDL.Func([ClientId], [IDL.Vec(Project)], ['query']),
  'getTasksByProject' : IDL.Func([ProjectId], [IDL.Vec(Task)], ['query']),
  'updateClient' : IDL.Func([UpdateClientArgs], [IDL.Opt(Client)], []),
  'updateLink' : IDL.Func([UpdateLinkArgs], [IDL.Opt(Link)], []),
  'updateNote' : IDL.Func([UpdateNoteArgs], [IDL.Opt(Note)], []),
  'updateProject' : IDL.Func([UpdateProjectArgs], [IDL.Opt(Project)], []),
  'updateTask' : IDL.Func([UpdateTaskArgs], [IDL.Opt(Task)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreateClientArgs = IDL.Record({
    'name' : IDL.Text,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ClientId = IDL.Nat;
  const Timestamp = IDL.Nat;
  const Client = IDL.Record({
    'id' : ClientId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ParentType = IDL.Variant({ 'Client' : IDL.Null, 'Project' : IDL.Null });
  const CreateLinkArgs = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'parentId' : IDL.Nat,
    'parentType' : ParentType,
  });
  const LinkId = IDL.Nat;
  const Link = IDL.Record({
    'id' : LinkId,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'parentId' : IDL.Nat,
    'parentType' : ParentType,
  });
  const CreateNoteArgs = IDL.Record({
    'content' : IDL.Text,
    'parentId' : IDL.Nat,
    'parentType' : ParentType,
  });
  const NoteId = IDL.Nat;
  const Note = IDL.Record({
    'id' : NoteId,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'parentId' : IDL.Nat,
    'parentType' : ParentType,
  });
  const ProjectStatus = IDL.Variant({
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const CreateProjectArgs = IDL.Record({
    'status' : ProjectStatus,
    'clientId' : ClientId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'paidAmount' : IDL.Nat,
    'budget' : IDL.Nat,
  });
  const ProjectId = IDL.Nat;
  const Project = IDL.Record({
    'id' : ProjectId,
    'status' : ProjectStatus,
    'clientId' : ClientId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'paidAmount' : IDL.Nat,
    'budget' : IDL.Nat,
  });
  const CreateTaskArgs = IDL.Record({
    'name' : IDL.Text,
    'projectId' : ProjectId,
  });
  const TaskId = IDL.Nat;
  const Task = IDL.Record({
    'id' : TaskId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isDone' : IDL.Bool,
    'projectId' : ProjectId,
  });
  const DashboardStats = IDL.Record({
    'activeProjects' : IDL.Nat,
    'totalClients' : IDL.Nat,
    'completedProjects' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
  });
  const UpdateClientArgs = IDL.Record({
    'id' : ClientId,
    'name' : IDL.Text,
    'businessName' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UpdateLinkArgs = IDL.Record({
    'id' : LinkId,
    'url' : IDL.Text,
    'title' : IDL.Text,
  });
  const UpdateNoteArgs = IDL.Record({ 'id' : NoteId, 'content' : IDL.Text });
  const UpdateProjectArgs = IDL.Record({
    'id' : ProjectId,
    'status' : ProjectStatus,
    'clientId' : ClientId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'paidAmount' : IDL.Nat,
    'budget' : IDL.Nat,
  });
  const UpdateTaskArgs = IDL.Record({
    'id' : TaskId,
    'name' : IDL.Text,
    'isDone' : IDL.Bool,
  });
  
  return IDL.Service({
    'createClient' : IDL.Func([CreateClientArgs], [Client], []),
    'createLink' : IDL.Func([CreateLinkArgs], [Link], []),
    'createNote' : IDL.Func([CreateNoteArgs], [Note], []),
    'createProject' : IDL.Func([CreateProjectArgs], [Project], []),
    'createTask' : IDL.Func([CreateTaskArgs], [Task], []),
    'deleteClient' : IDL.Func([ClientId], [IDL.Bool], []),
    'deleteLink' : IDL.Func([LinkId], [IDL.Bool], []),
    'deleteNote' : IDL.Func([NoteId], [IDL.Bool], []),
    'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
    'deleteTask' : IDL.Func([TaskId], [IDL.Bool], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getClient' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
    'getClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getLinksByParent' : IDL.Func(
        [IDL.Nat, ParentType],
        [IDL.Vec(Link)],
        ['query'],
      ),
    'getNotesByParent' : IDL.Func(
        [IDL.Nat, ParentType],
        [IDL.Vec(Note)],
        ['query'],
      ),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
    'getProjectsByClient' : IDL.Func([ClientId], [IDL.Vec(Project)], ['query']),
    'getTasksByProject' : IDL.Func([ProjectId], [IDL.Vec(Task)], ['query']),
    'updateClient' : IDL.Func([UpdateClientArgs], [IDL.Opt(Client)], []),
    'updateLink' : IDL.Func([UpdateLinkArgs], [IDL.Opt(Link)], []),
    'updateNote' : IDL.Func([UpdateNoteArgs], [IDL.Opt(Note)], []),
    'updateProject' : IDL.Func([UpdateProjectArgs], [IDL.Opt(Project)], []),
    'updateTask' : IDL.Func([UpdateTaskArgs], [IDL.Opt(Task)], []),
  });
};

export const init = ({ IDL }) => { return []; };