/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpdateNoteArgs {
    id: NoteId;
    content: string;
}
export interface UpdateLinkArgs {
    id: LinkId;
    url: string;
    title: string;
}
export type Timestamp = bigint;
export type NoteId = bigint;
export interface CreateProjectArgs {
    status: ProjectStatus;
    clientId: ClientId;
    name: string;
    description: string;
    deadline: string;
    paidAmount: bigint;
    budget: bigint;
}
export type ClientId = bigint;
export interface Client {
    id: ClientId;
    name: string;
    createdAt: Timestamp;
    businessName: string;
    email: string;
    phone: string;
}
export interface Task {
    id: TaskId;
    name: string;
    createdAt: Timestamp;
    isDone: boolean;
    projectId: ProjectId;
}
export interface UpdateClientArgs {
    id: ClientId;
    name: string;
    businessName: string;
    email: string;
    phone: string;
}
export interface CreateClientArgs {
    name: string;
    businessName: string;
    email: string;
    phone: string;
}
export interface DashboardStats {
    activeProjects: bigint;
    totalClients: bigint;
    completedProjects: bigint;
    totalEarnings: bigint;
}
export interface CreateTaskArgs {
    name: string;
    projectId: ProjectId;
}
export interface UpdateTaskArgs {
    id: TaskId;
    name: string;
    isDone: boolean;
}
export type LinkId = bigint;
export type TaskId = bigint;
export type ProjectId = bigint;
export interface CreateLinkArgs {
    url: string;
    title: string;
    parentId: bigint;
    parentType: ParentType;
}
export interface CreateNoteArgs {
    content: string;
    parentId: bigint;
    parentType: ParentType;
}
export interface Project {
    id: ProjectId;
    status: ProjectStatus;
    clientId: ClientId;
    name: string;
    createdAt: Timestamp;
    description: string;
    deadline: string;
    paidAmount: bigint;
    budget: bigint;
}
export interface UpdateProjectArgs {
    id: ProjectId;
    status: ProjectStatus;
    clientId: ClientId;
    name: string;
    description: string;
    deadline: string;
    paidAmount: bigint;
    budget: bigint;
}
export interface Link {
    id: LinkId;
    url: string;
    title: string;
    createdAt: Timestamp;
    parentId: bigint;
    parentType: ParentType;
}
export interface Note {
    id: NoteId;
    content: string;
    createdAt: Timestamp;
    parentId: bigint;
    parentType: ParentType;
}
export enum ParentType {
    Client = "Client",
    Project = "Project"
}
export enum ProjectStatus {
    InProgress = "InProgress",
    Completed = "Completed",
    Pending = "Pending"
}
export interface backendInterface {
    createClient(args: CreateClientArgs): Promise<Client>;
    createLink(args: CreateLinkArgs): Promise<Link>;
    createNote(args: CreateNoteArgs): Promise<Note>;
    createProject(args: CreateProjectArgs): Promise<Project>;
    createTask(args: CreateTaskArgs): Promise<Task>;
    deleteClient(id: ClientId): Promise<boolean>;
    deleteLink(id: LinkId): Promise<boolean>;
    deleteNote(id: NoteId): Promise<boolean>;
    deleteProject(id: ProjectId): Promise<boolean>;
    deleteTask(id: TaskId): Promise<boolean>;
    getAllProjects(): Promise<Array<Project>>;
    getClient(id: ClientId): Promise<Client | null>;
    getClients(): Promise<Array<Client>>;
    getDashboardStats(): Promise<DashboardStats>;
    getLinksByParent(parentId: bigint, parentType: ParentType): Promise<Array<Link>>;
    getNotesByParent(parentId: bigint, parentType: ParentType): Promise<Array<Note>>;
    getProject(id: ProjectId): Promise<Project | null>;
    getProjectsByClient(clientId: ClientId): Promise<Array<Project>>;
    getTasksByProject(projectId: ProjectId): Promise<Array<Task>>;
    updateClient(args: UpdateClientArgs): Promise<Client | null>;
    updateLink(args: UpdateLinkArgs): Promise<Link | null>;
    updateNote(args: UpdateNoteArgs): Promise<Note | null>;
    updateProject(args: UpdateProjectArgs): Promise<Project | null>;
    updateTask(args: UpdateTaskArgs): Promise<Task | null>;
}
import type { Client as _Client, ClientId as _ClientId, CreateLinkArgs as _CreateLinkArgs, CreateNoteArgs as _CreateNoteArgs, CreateProjectArgs as _CreateProjectArgs, Link as _Link, LinkId as _LinkId, Note as _Note, NoteId as _NoteId, ParentType as _ParentType, Project as _Project, ProjectId as _ProjectId, ProjectStatus as _ProjectStatus, Task as _Task, Timestamp as _Timestamp, UpdateProjectArgs as _UpdateProjectArgs } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createClient(arg0: CreateClientArgs): Promise<Client> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(arg0);
            return result;
        }
    }
    async createLink(arg0: CreateLinkArgs): Promise<Link> {
        if (this.processError) {
            try {
                const result = await this.actor.createLink(to_candid_CreateLinkArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Link_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLink(to_candid_CreateLinkArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Link_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNote(arg0: CreateNoteArgs): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(to_candid_CreateNoteArgs_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Note_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(to_candid_CreateNoteArgs_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Note_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProject(arg0: CreateProjectArgs): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_CreateProjectArgs_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Project_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_CreateProjectArgs_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Project_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTask(arg0: CreateTaskArgs): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0);
            return result;
        }
    }
    async deleteClient(arg0: ClientId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteLink(arg0: LinkId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLink(arg0);
            return result;
        }
    }
    async deleteNote(arg0: NoteId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async deleteProject(arg0: ProjectId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: ClientId): Promise<Client | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClients();
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getLinksByParent(arg0: bigint, arg1: ParentType): Promise<Array<Link>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLinksByParent(arg0, to_candid_ParentType_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLinksByParent(arg0, to_candid_ParentType_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesByParent(arg0: bigint, arg1: ParentType): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByParent(arg0, to_candid_ParentType_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByParent(arg0, to_candid_ParentType_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: ProjectId): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectsByClient(arg0: ClientId): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectsByClient(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectsByClient(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByProject(arg0: ProjectId): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByProject(arg0);
            return result;
        }
    }
    async updateClient(arg0: UpdateClientArgs): Promise<Client | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLink(arg0: UpdateLinkArgs): Promise<Link | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLink(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLink(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNote(arg0: UpdateNoteArgs): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProject(arg0: UpdateProjectArgs): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(to_candid_UpdateProjectArgs_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(to_candid_UpdateProjectArgs_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTask(arg0: UpdateTaskArgs): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Link_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Link): Link {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ParentType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ParentType): ParentType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Client]): Client | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Link]): Link | null {
    return value.length === 0 ? null : from_candid_Link_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Note]): Note | null {
    return value.length === 0 ? null : from_candid_Note_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NoteId;
    content: string;
    createdAt: _Timestamp;
    parentId: bigint;
    parentType: _ParentType;
}): {
    id: NoteId;
    content: string;
    createdAt: Timestamp;
    parentId: bigint;
    parentType: ParentType;
} {
    return {
        id: value.id,
        content: value.content,
        createdAt: value.createdAt,
        parentId: value.parentId,
        parentType: from_candid_ParentType_n7(_uploadFile, _downloadFile, value.parentType)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    status: _ProjectStatus;
    clientId: _ClientId;
    name: string;
    createdAt: _Timestamp;
    description: string;
    deadline: string;
    paidAmount: bigint;
    budget: bigint;
}): {
    id: ProjectId;
    status: ProjectStatus;
    clientId: ClientId;
    name: string;
    createdAt: Timestamp;
    description: string;
    deadline: string;
    paidAmount: bigint;
    budget: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n19(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        deadline: value.deadline,
        paidAmount: value.paidAmount,
        budget: value.budget
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LinkId;
    url: string;
    title: string;
    createdAt: _Timestamp;
    parentId: bigint;
    parentType: _ParentType;
}): {
    id: LinkId;
    url: string;
    title: string;
    createdAt: Timestamp;
    parentId: bigint;
    parentType: ParentType;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        createdAt: value.createdAt,
        parentId: value.parentId,
        parentType: from_candid_ParentType_n7(_uploadFile, _downloadFile, value.parentType)
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    InProgress: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): ProjectStatus {
    return "InProgress" in value ? ProjectStatus.InProgress : "Completed" in value ? ProjectStatus.Completed : "Pending" in value ? ProjectStatus.Pending : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Client: null;
} | {
    Project: null;
}): ParentType {
    return "Client" in value ? ParentType.Client : "Project" in value ? ParentType.Project : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Link>): Array<Link> {
    return value.map((x)=>from_candid_Link_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Array<Note> {
    return value.map((x)=>from_candid_Note_n11(_uploadFile, _downloadFile, x));
}
function to_candid_CreateLinkArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateLinkArgs): _CreateLinkArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateNoteArgs_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateNoteArgs): _CreateNoteArgs {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_CreateProjectArgs_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProjectArgs): _CreateProjectArgs {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_ParentType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ParentType): _ParentType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProjectArgs_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProjectArgs): _UpdateProjectArgs {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    parentId: bigint;
    parentType: ParentType;
}): {
    content: string;
    parentId: bigint;
    parentType: _ParentType;
} {
    return {
        content: value.content,
        parentId: value.parentId,
        parentType: to_candid_ParentType_n3(_uploadFile, _downloadFile, value.parentType)
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ProjectStatus;
    clientId: ClientId;
    name: string;
    description: string;
    deadline: string;
    paidAmount: bigint;
    budget: bigint;
}): {
    status: _ProjectStatus;
    clientId: _ClientId;
    name: string;
    description: string;
    deadline: string;
    paidAmount: bigint;
    budget: bigint;
} {
    return {
        status: to_candid_ProjectStatus_n15(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        name: value.name,
        description: value.description,
        deadline: value.deadline,
        paidAmount: value.paidAmount,
        budget: value.budget
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    title: string;
    parentId: bigint;
    parentType: ParentType;
}): {
    url: string;
    title: string;
    parentId: bigint;
    parentType: _ParentType;
} {
    return {
        url: value.url,
        title: value.title,
        parentId: value.parentId,
        parentType: to_candid_ParentType_n3(_uploadFile, _downloadFile, value.parentType)
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProjectId;
    status: ProjectStatus;
    clientId: ClientId;
    name: string;
    description: string;
    deadline: string;
    paidAmount: bigint;
    budget: bigint;
}): {
    id: _ProjectId;
    status: _ProjectStatus;
    clientId: _ClientId;
    name: string;
    description: string;
    deadline: string;
    paidAmount: bigint;
    budget: bigint;
} {
    return {
        id: value.id,
        status: to_candid_ProjectStatus_n15(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        name: value.name,
        description: value.description,
        deadline: value.deadline,
        paidAmount: value.paidAmount,
        budget: value.budget
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    InProgress: null;
} | {
    Completed: null;
} | {
    Pending: null;
} {
    return value == ProjectStatus.InProgress ? {
        InProgress: null
    } : value == ProjectStatus.Completed ? {
        Completed: null
    } : value == ProjectStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ParentType): {
    Client: null;
} | {
    Project: null;
} {
    return value == ParentType.Client ? {
        Client: null
    } : value == ParentType.Project ? {
        Project: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
